### ISSUE TITLE
Missing License

### ISSUE THREAD

**Issue by arvvoid** [yuppity/ttml2srt#1]
Hello,

a license is missing, is this an error or is intentional?

I am using this code with some minor modifications in my hbo go add-on for kodi under GPL license [TTML2SRT Class in the Add-on](https://github.com/arvvoid/plugin.video.hbogoeu/blob/master/hbogolib/ttml2srt.py). Am I permitted to do so?

**Comment by yuppity** [comment]
Sorry for the way-too-late reply. In case this is still pertinent: yes, feel free to do so.

EDIT: For clarity, this is addressed by 306ddf3b3f75643f0a8d5f82404f425c57e55bdf (didn't think to reference this in the commit)
